### ISSUE TITLE
PDF 版的讲义

### ISSUE THREAD

**Issue by inkydragon** [QuantumBFS/SSSS#1]
有源文件当然好，不过有 PDF 看就行，也不存在兼容性问题。
PDF 扔到 Release 里也行。

(折腾了一下午硬是 `keynote` 转 PDF 不成功

**Comment by Roger-luo** [comment]
这个不是讲义，是海报。

**Comment by inkydragon** [comment]
好吧，并没有能看到内容

**Comment by GiggleLiu** [comment]
@wangleiphy 要不给你海报换个名字叫SongShanHu2019_poster ？
