### ISSUE TITLE
Possible BUG in TwoQubit-VQE.ipynb

### ISSUE THREAD

**Issue by frankwswang** [QuantumBFS/SSSS#6]
In the last `ChainBlock` in `Out[370]`, the 2 MeasureBlocks are printed as:
```
   ├─ Measure{2,1,AbstractBlock}
   └─ Measure{2,1,AbstractBlock}
```
Should one be `Measure{2,2,AbstractBlock}` for it should be put on the 2nd line of the circuit? Maybe you should fix the function `twoqubit_circuit` in `Out[369]`.

**Comment by GiggleLiu** [comment]
This is not a bug, the second type parameter means "how many qubits" got measured. So, it is the printing should be improved. :sorry

**Comment by quantumbfs0** [comment]
@GiggleLiu Shall we close this if you already improved print?
